from rabbit import Rabbit

rabbit1 = Rabbit("Snowball", "White")
rabbits = []
rabbits.append(rabbit1)
print(rabbit1)
rabbit1.set_gender("Girl")
rabbit1.set_legs(4)
rabbit1.set_sleep()
rabbit1.get_fav_food("Broccoli")
rabbit1.set_fav_human("Gracie-Lea")
rabbit1.get_fav_play_item("My Tunnel")
rabbit1.set_size("Small")
rabbit1.set_age(1)

rabbit2 = Rabbit("Lucky", "Black")
rabbits.append(rabbit2)
print(rabbit2)
rabbit2.set_gender("Girl")
rabbit2.set_legs(4)
rabbit2.set_sleep()
rabbit2.get_fav_food("Cauliflower leaves")
rabbit2.set_fav_human("Gracie-Lea")
rabbit2.get_fav_play_item("My ball")
rabbit2.set_size("Small")
rabbit2.set_age(1)